import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { createHarness, projectFixture, until, wav } from "./helpers.js";

test("HTTP: queued projects, priority retouch, timeline during generation, version selection and real MP4 export", { timeout: 30_000 }, async (t) => {
  const h = await createHarness(); t.after(() => h.cleanup());
  const old = projectFixture("old");
  old.images[0].versions.push({ id: "alternative", filename: "alternative.png" });
  await h.seed(old); await h.start();
  const a = await h.create("A.wav");
  await until(() => h.pending().length === 3);
  const b = await h.create("B.wav");
  assert.equal((await h.get(b)).status, "queued");
  const sceneState = await h.get(a);
  assert.equal(sceneState.images.length, 4);
  assert.ok(sceneState.images.every((image) => image.description && !image.src));
  const moved = await h.post(`/api/projects/${a}/scenes/1/timing`, { start: 1.4 });
  assert.equal(moved.status, 200);
  assert.equal(moved.data.images[1].timelineStart, 1.4);
  assert.equal((await fetch(`${h.url}/api/projects/${a}`, { method: "DELETE" })).status, 409);
  const retouch = await h.post("/api/projects/old/scenes/0/regenerate", { instructions: "Une flèche bleue" });
  assert.equal(retouch.status, 202);
  assert.equal(retouch.data.images[0].regeneration.status, "queued");
  assert.equal((await h.post("/api/projects/old/scenes/0/regenerate")).status, 409);
  h.pending()[0].complete();
  await until(() => h.pending().some((record) => record.url.endsWith("/edits")));
  assert.equal((await h.get(b)).status, "queued");
  await h.post("/api/projects/old/scenes/0/select-version", { versionId: "alternative" });
  h.pending().find((record) => record.url.endsWith("/edits")).complete();
  await until(async () => (await h.get("old")).images[0].regeneration.status === "succeeded");
  assert.equal((await h.get("old")).images[0].selectedVersionId, "alternative");
  assert.equal((await h.get("old")).images[0].versions.length, 3);
  h.autoImages = true;
  h.pending().forEach((record) => record.complete());
  await until(async () => (await h.get(b)).status === "completed");
  assert.equal((await h.get(a)).status, "completed");
  assert.equal((await h.get(a)).images[1].timelineStart, 1.4);
  assert.ok(h.peak <= 3, `Global concurrency exceeded: ${h.peak}`);
  await h.post("/api/projects/old/scenes/0/timing", { start: 0.5 });
  const exported = await h.post("/api/projects/old/export");
  assert.equal(exported.status, 202);
  await h.post("/api/projects/old/scenes/1/timing", { start: 1.2 });
  const ready = await until(async () => {
    const state = await h.get("old");
    if (state.export.status === "failed") throw new Error(state.export.error);
    return state.export.status === "ready" && state;
  });
  assert.equal(ready.export.isCurrent, false);
  const manifest = JSON.parse(await fs.readFile(path.join(h.projects, "old", "project.json")));
  assert.equal(manifest.export.snapshot.images[1].start, 2);
  const video = await fetch(`${h.url}${ready.export.downloadUrl}`);
  assert.equal(video.status, 200);
  const bytes = Buffer.from(await video.arrayBuffer());
  assert.ok(bytes.includes(Buffer.from("ftyp")));
  const previousCalls = h.records.length;
  await h.stop(); await h.start();
  assert.equal((await h.get(a)).images[1].timelineStart, 1.4);
  assert.equal((await h.get("old")).images[0].selectedVersionId, "alternative");
  assert.equal(h.records.length, previousCalls);
});

test("restart: checkpoints, queued source, running retouch and committed PNG recovery", { timeout: 30_000 }, async (t) => {
  const h = await createHarness({ concurrency: 2 }); t.after(() => h.cleanup());
  const a = projectFixture("resume", { status: "working", count: 3, ready: 1 });
  a.images[1].initialTask.status = "running";
  a.images[1].timelineStart = 1.75;
  await h.seed(a);
  // This output was committed before the manifest was updated.
  await fs.writeFile(path.join(h.projects, a.id, "images", "0001.png"), h.png);
  const old = projectFixture("retouch");
  old.images[0].regeneration = { id: "recover-edit", status: "running", attempts: 1, filename: "recovered.png", versionId: "recovered", referenceFilename: "0.png", referenceVersionId: "original", instructions: "Bleu", quality: "medium" };
  await h.seed(old);
  const queued = projectFixture("queued", { status: "queued", count: 0, ready: 0 });
  queued.audioFilename = null; queued.sourceFilename = "source.wav"; queued.words = []; queued.pipeline = {};
  queued.createdAt = "2026-10-02T10:00:00.000Z";
  await h.seed(queued);
  await fs.writeFile(path.join(h.projects, queued.id, "source.wav"), wav());
  await h.start();
  await until(() => h.pending().length === 2);
  assert.ok(h.pending().some((record) => record.url.endsWith("/edits")));
  assert.ok(h.pending().some((record) => record.body.includes("resume-scene-2")));
  assert.ok(!h.records.some((record) => record.body.includes("resume-scene-0") || record.body.includes("resume-scene-1")));
  assert.equal((await h.get("resume")).images[1].timelineStart, 1.75);
  assert.equal((await h.get("queued")).status, "queued");
  // Terminate with two HTTP calls still running, then recreate the process.
  await h.stop(); h.autoImages = true; await h.start();
  await until(async () => (await h.get("queued")).status === "completed");
  const recovered = await h.get("resume");
  assert.equal(recovered.status, "completed");
  assert.equal(recovered.images[1].timelineStart, 1.75);
  assert.equal(recovered.images[1].versions.length, 1);
  assert.equal((await h.get("retouch")).images[0].regeneration.status, "succeeded");
  assert.equal((await h.get("retouch")).images[0].versions.length, 2);
  assert.equal(h.records.filter((record) => record.url === "/v1/audio/transcriptions").length, 1);
  assert.ok(!h.records.some((record) => record.body.includes("resume-scene-0") || record.body.includes("resume-scene-1")));
});

test("permanent image errors stay local to the scene and do not stop the following project", { timeout: 15_000 }, async (t) => {
  const h = await createHarness({ concurrency: 1 }); t.after(() => h.cleanup());
  const a = projectFixture("bad-image", { status: "queued", count: 1, ready: 0 });
  const b = projectFixture("following", { status: "queued", count: 1, ready: 0 }); b.createdAt = "2026-10-02T10:00:00Z";
  await h.seed(a); await h.seed(b); await h.start();
  await until(() => h.pending().length === 1);
  h.pending()[0].complete(400, { message: "Image rejected", code: "content_policy_violation", type: "invalid_request_error" });
  await until(() => h.pending().length === 1 && h.pending()[0].body.includes("following-scene-0"));
  h.pending()[0].complete();
  await until(async () => (await h.get(b.id)).status === "completed");
  assert.equal((await h.get(a.id)).images[0].initialTask.status, "failed");
  assert.equal(h.records.filter((record) => record.body.includes("bad-image-scene-0")).length, 1);
  const retried = await h.post(`/api/projects/${a.id}/scenes/0/regenerate`, { instructions: "Une métaphore neutre" });
  assert.equal(retried.status, 202);
  await until(() => h.pending().length === 1);
  h.pending()[0].complete();
  await until(async () => (await h.get(a.id)).images[0].regeneration.status === "succeeded");
  assert.equal((await h.get(a.id)).images[0].error, null);
});
